### PR TITLE
Find dwell times

### PR DESCRIPTION
**Pull request by niravi**
To Do:
- [x] visualize the two dwell events as two different groups of color on the map

### CODE REVIEW

**Review by apulverizer — CHANGES_REQUESTED** [review]
- I think the time range query builder can be simplified. For instance there is no need to check `tracks_query` in the first  if block.
- Does this account for if the dwell event coincided with the user turning off tracking within the polygon? I think this would not be detected, you might need to add some other check for that.
- I think it would be good to create a data frame that lists all of the dwell events, rather than printing them
- Then you could visually show some of the dwell events on a map 

- I got an error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-450ab3de7681> in <module>
      2 # format to UTC
      3 if start_date:
----> 4     local_start_date = pendulum.from_format(start_date, "MM/DD/YYYY hh:mm:ss", tz=timezone,formatter='alternative').in_tz('UTC').format("%Y-%m-%d %H:%M:%S")
      5     if tracks_query:
      6         tracks_query = tracks_query + " AND "

TypeError: from_format() got an unexpected keyword argument 'formatter'
```

```
tracks_layer = tracks_query + f"AND created_user='{user.attributes['created_user']}"
```

Should this be `query = tracks_query + …` Looks like this will blow up if there are multiple users returned

You should only buffer each feature once, instead of for each user

**Comment by niravi** [comment]
> * I think the time range query builder can be simplified. For instance there is no need to check `tracks_query` in the first  if block.

Will fix

> * Does this account for if the dwell event coincided with the user turning off tracking within the polygon? I think this would not be detected, you might need to add some other check for that.

This only finds the tracks when the user enters the polygon and exits it. However, the last block of code will report it separately if the user enters the polygon and is not detected leaving it (i.e. `start_date` is set, but `end_date` is not).

> * I think it would be good to create a data frame that lists all of the dwell events, rather than printing them

Sounds good, will do this

> * I got an error:
> 
> ```
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-5-450ab3de7681> in <module>
>       2 # format to UTC
>       3 if start_date:
> ----> 4     local_start_date = pendulum.from_format(start_date, "MM/DD/YYYY hh:mm:ss", tz=timezone,formatter='alternative').in_tz('UTC').format("%Y-%m-%d %H:%M:%S")
>       5     if tracks_query:
>       6         tracks_query = tracks_query + " AND "
> 
> TypeError: from_format() got an unexpected keyword argument 'formatter'
> ```

Can you check which version of pendulum you have installed? I have seen this error in pendulum 2.0, which is why the env file in this repo is set to 1.4.4. The library appears to have deprecated a lot of parameters in between 1 and 2

> ```
> tracks_layer = tracks_query + f"AND created_user='{user.attributes['created_user']}"
> ```
> 
> Should this be `query = tracks_query + …` Looks like this will blow up if there are multiple users returned

Yeah this is a typo - will fix

> You should only buffer each feature once, instead of for each user

👍

**Comment by niravi** [comment]
@apulverizer I have addressed your feedback - both printing dwell events and storing them separately as a dataframe in order to visualize them. I have also added a step to visualize those separate dataframes. Ready for review

**Comment by apulverizer** [comment]
@niravi yeah downgrading pendulum worked

Adding that map at the end helps a lot. I was thinking the dataframe would be like:

Dwell ID | Polygon ID | Username | Start Time | End Time |
|--------|------------|------------|------------|----------|
1 | 1 | admin | 2020-04-14 14:50:51.917000 | 2020-04-14 14:54:25.935000

**Comment by niravi** [comment]
@apulverizer I have stored each dwell event into a dataframe and then printed out the dataframe once the iteration is complete

**Review by apulverizer — APPROVED** [review]
Looks pretty good. Couple minor suggestions:

1. Don't `print` the dataframe, just do `final_df` so it renders the df in html
2. Remove the extra `map2.take_screenshot()` call
3. Remove the last extra cell
4. Do a clean run so the cell ids are sequential.

**Pull request merged**
